controllers:
    resource: ../src/Controller/
    type: attribute

login:
    path: /login
    controller: App\Controller\SecurityController::login

register:
    path: /register
    controller: App\Controller\SecurityController::register

frontend:
    path: /
    controller: App\Controller\FrontendController::index

index:
    path: /
    controller: App\Controller\SecurityController::login
